# SPDX-FileCopyrightText: 2026 Jan Matyas <info@janmatyas.net>
# SPDX-License-Identifier: CC0-1.0

name: Check compliance with REUSE spec
on: push
jobs:
  reuse_compliance_check:
    runs-on: ubuntu-26.04
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v6
      - name: Install the reuse linter tool
        run: |
          python3 -m pip install --user reuse==6.2.0
      - name: Perform the check
        run: |
          reuse lint
